//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_OOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUONXE
    {
        public int MaMuonXe { get; set; }
        public System.DateTime ThoiGianMuon { get; set; }
        public System.DateTime ThoiGianTra { get; set; }
        public Nullable<int> MaXeMuon { get; set; }
        public Nullable<int> MaTheMuon { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual XE XE { get; set; }
    }
}
